blogapp/urls.py
from django.urls import path
from . import views

app_name = 'blogapp'
urlpatterns = [
    path('', views.home, name='home'),
    path('category/<str:path_name>/', views.category, name='category'),
    path('post/<int:post_id>/', views.blog_post, name='post'),
    path('about/', views.about_me, name='about')
]

blogproj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blogapp.urls')),
    path('julie/', include('julieapp.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

julieapp/urls.py
from django.urls import path
from . import views

app_name = 'julieapp'
urlpatterns = [
    path('login/', views.login_request, name='login'),
    path('logout/', views.logout_request, name='logout'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('create/', views.create_post, name='create'),
    path('edit/<str:post_id>/', views.edit_post, name='edit'),
    path('delete/<int:post_id>/', views.delete_post, name='delete'),
]

blogapp/models.py
from django.db import models

class Category(models.Model):
    name = models.CharField(max_length=200)
    image = models.ImageField(upload_to='blog_category_images/')
    description = models.CharField(blank=True, max_length=200)
    path_name = models.CharField(max_length=200)

    def __str__(self):
        return self.name

class BlogPost(models.Model):
    title = models.CharField(max_length=200)
    body = models.TextField()
    image = models.ImageField(blank=True, null=True, upload_to='blog_post_images/')
    date_created = models.DateTimeField(auto_now_add=True)
    categories = models.ManyToManyField(Category, related_name='blog_posts')
    description = models.CharField(blank=True, max_length=200)

    def __str__(self):
        return self.title

julieapp/models.py
from django.db import models

julieapp/forms.py
from django.forms import ModelForm
from blogapp.models import BlogPost

class BlogForm(ModelForm):
    class Meta:
        model = BlogPost
        exclude = []

blogapp/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpRequest
from .models import BlogPost, Category
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.forms import AuthenticationForm

def home(request):
    categories = Category.objects.all()
    for category in categories:
        print(category.id)
    print(categories)
    context = {
        'categories': categories
    }
    return render(request, 'blogapp/home.html', context)

def category(request, path_name):
    category = Category.objects.get(path_name=path_name)
    posts = category.blog_posts.all().order_by('-date_created')
    context = {
        'posts' : posts,
        'category': category,
    }
    return render(request, 'blogapp/category.html', context)

def blog_post(request, post_id):
    post = BlogPost.objects.get(id=post_id)
    categories = Category.objects.all()
    for category in categories:
        print(category.id)
    print(categories)
    context = {
        'post' : post,
        'categories' : categories,
    }
    return render(request, 'blogapp/blogPost.html', context)

def about_me(request):
    return render(request, 'blogapp/about.html')

julieapp/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404
from blogapp.models import BlogPost, Category
from django.db.models import Q
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm
from django.http import HttpResponse, HttpRequest, HttpResponseRedirect
from django.contrib import messages
from .forms import BlogForm

def login_request(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            print('here')
            login(request, user)
            messages.info(request, f"You are now logged in as {username}. Welcome back!")
            next = request.GET.get('next', reverse('julieapp:dashboard'))
            return HttpResponseRedirect(next)
        else:
            messages.error(request, "Invalid username or password.")
    return render(request, 'julieapp/login.html') 

@login_required
def logout_request(request):
    logout(request)
    return HttpResponseRedirect(reverse('julieapp:login'))

@login_required
def dashboard(request):
    posts = BlogPost.objects.all().order_by('-date_created')
    search = request.GET.get('search', '')
    category = request.GET.get('category', '')        
    categories = Category.objects.all()
    if search !='' or category!='':
        posts = posts.filter(Q(title__icontains=search)
                             & Q(categories__name__icontains=category))
    context = {
        'posts': posts,
        "search": search,
        "categories": categories,
        "selected_category": category,
    }
    return render(request, 'julieapp/dashboard.html', context)

@login_required
def create_post(request):
    if request.method == 'POST':
        form = BlogForm(request.POST, request.FILES)
        if form.is_valid():
            print('here')
            post = form.save()
            return HttpResponseRedirect(reverse('julieapp:dashboard'))
    else:
        form = BlogForm()
    context = {
        'form': form
    }
    return render(request, 'julieapp/create.html', context)

@login_required
def edit_post(request, post_id):
    post = BlogPost.objects.get(id=post_id)
    if request.method =='POST':
        form = BlogForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('julieapp:dashboard'))
    else:
        form = BlogForm(instance=post)
    context = {
        'form': form,
        'post_to_delete': post,
    }
    return render(request, 'julieapp/edit.html', context)

@login_required
def delete_post(request, post_id):
    post_to_delete = get_object_or_404(BlogPost, id=post_id)
    post_to_delete.delete()
    return HttpResponseRedirect(reverse('julieapp:dashboard'))

blogapp/templates/blogapp/about.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">

    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
        integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

    <!-- font -->
    <link href="https://fonts.googleapis.com/css2?family=Dawning+of+a+New+Day&display=swap" rel="stylesheet">

    <title>About</title>
    <style>
        @media only screen and (max-width: 600px) {
            nav .brand-logo {
                /* z-index: 100; */
                left: 127.5px !important;
                top: 5px;
                font-size: 34px !important;
            }
        }

        @media only screen and (max-width: 703px) {
            .brand-logo {
                white-space: nowrap;
                font-size: 19px !important;
            }

            h5 {
                font-size: 16px;
                white-space: nowrap;
            }
        }

        .social-foot {
            padding-left: .75rem;
        }

        body {
            display: flex;
            min-height: 100vh;
            flex-direction: column;
        }

        main {
            flex: 1 0 auto;
        }

        .nav-wrapper {
            background-color: rgb(251, 245, 239);
        }

        .brand-logo {
            font-family: 'Dawning of a New Day', cursive;
            font-size: 53px !important;
            margin-top: 4px;
            color: rgb(216, 163, 110) !important;
            font-weight: lighter !important;
        }

        nav {
            height: 80px;
        }

        .card-row {
            display: flex;
            justify-content: center;
            align-items: center;
        }

        .btn-floating i {
            font-size: 2rem;
        }

        .slide-social {
            padding-left: 10px;
        }

        body {
            background-color: rgb(248, 237, 235);
        }

        .page-footer {
            background-color: rgb(251, 245, 239);
        }

        h5 {
            color: rgb(216, 163, 110) !important;
        }

        .subscribe {
            color: rgb(216, 163, 110) !important;
        }

        .btn-floating {
            background-color: rgb(216, 163, 110) !important;
        }

        nav .dropdown-trigger i {
            line-height: 80px !important;
        }

        .sidenav-trigger {
            line-height: 80px !important;
            height: 80px !important;
            display: flex;
            align-self: center;
        }

        .sidenav {
            background-color: rgb(251, 245, 239);
            color: black;
        }

        .sidenav li>a {
            color: rgb(216, 163, 110) !important;
        }

        .material-icons {
            color: rgb(216, 163, 110);
            height: 80px !important;
            line-height: 80px !important;
        }

        .dropdown-content {
            background-color: rgb(251, 245, 239);
        }

        .dropdown-content li>span {
            color: rgb(216, 163, 110) !important
        }

        li p {
            padding: 0 32px;
            font-size: 14px;
            font-weight: 500;
        }

        .slide-social {
            padding: 0 32px !important;
        }

        .about-image {
            width: 100%;
            height: auto;
            padding-top: 10px;
        }
    </style>
</head>

<body>
    <nav>
        <div class="nav-wrapper">
            <a href="{% url 'blogapp:home' %}" class="brand-logo center">All Shapes • About</a>
            <a href="#" data-target="slide-out" class="sidenav-trigger right"><i class="material-icons">menu</i></a>
        </div>
    </nav>

    <!-- side menu for mobile -->
    <ul id="slide-out" class="sidenav">
        <li><a href="{% url 'blogapp:about' %}">About</a></li>
        <li><a target="_blank" href="https://mailchi.mp/33a744da0f70/allshapes">Newsletter</a></li>
        <li>
            <div class="divider"></div>
        </li>
        <li>
            <p>Social Media</p>
        </li>
        <li>
            <div class="slide-social"><a href="" class="waves-effect pulse btn-floating">
                    <i class="fa fa-instagram"></i></a>
            </div>
        </li>
    </ul>

    <!-- About -->
    <main>
        <div class="container">
            <div class="row">
                <div class="col s12">
                    <img class="about-image" src="{% static 'blogapp/images/Confidence.jpeg' %}">
                </div>
                <div class="col s12 body-overflow">
                    <p>
                        Hello Folks! <br>
                        <br>
                        To start, I am fascinated by books, architecture, and plants. I was born and raised in Portland,
                        Oregon. Yes, a true Oregonian. I love my trees. I have always had an eye for fashion. I always
                        pictured myself helping other people evolve. I am a huge believer that happiness is the key to
                        success. If I am not out enjoying a hike, you will see me cooped up indoors brewing myself a cup
                        of coffee and watching classifical horror movies. I am all about women empowerment and achieving
                        your goals in life. Everyone is accepted and loved. I hope my words inspire you to achieve
                        greatness and become the best version of yourself. You are beautiful inside and out. Do not let
                        anyone ever take that away from you. <br> <br> Yours truly, Julie Alvarez.

                    </p>
                </div>
            </div>
        </div>
    </main>

    <footer class="page-footer z-depth-5">
        <div class="container">
            <div class="row">
                <div class="col s4">
                    <h5>Newsletter</h5>
                    <a class="subscribe" href="https://mailchi.mp/33a744da0f70/allshapes" target="_blank">Subscribe</a>
                </div>
                <div class="col s4">
                    <a href="{% url 'blogapp:about' %}">
                        <h5>About</h5>
                    </a>
                </div>
                <div class="col s4">
                    <h5>Keep in Touch</h5>
                    <div class="row social-foot">
                        <a href="" class="waves-effect pulse btn-floating">
                            <i class="fa fa-instagram"></i></a>
                    </div>
                </div>
            </div>
        </div>
    </footer>


    <script>
        document.addEventListener('DOMContentLoaded', function () {
            var elems = document.querySelectorAll('.sidenav');
            var instances = M.Sidenav.init(elems, { edge: 'right' });
        });

        // Initialize collapsible (uncomment the lines below if you use the dropdown variation)
        // var collapsibleElem = document.querySelector('.collapsible');
        // var collapsibleInstance = M.Collapsible.init(collapsibleElem, options);
    </script>
</body>

</html>

blogapp/templates/blogapp/blogPost.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">

    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
        integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    
    <!-- font -->
    <link href="https://fonts.googleapis.com/css2?family=Dawning+of+a+New+Day&display=swap" rel="stylesheet">

    <title>{{ post.title }}</title>
    <style>
         @media only screen and (max-width: 600px) {
            .overlay {
                opacity: 1 !important;
            }

            nav .brand-logo {
                /* z-index: 100; */
                left: 155px !important;
                top: 5px;
                font-size: 34px !important;
            }
        }
        @media only screen and (max-width: 703px) {
            .brand-logo {
                white-space: nowrap;
                font-size: 19px !important;
            }
            h5 {
                font-size: 16px;
                white-space: nowrap;
            }
        }
        .social-foot {
            padding-left: .75rem;
        }
        .body-overflow {
            overflow: auto;
            max-height: 887px;
        }
        body {
            display: flex;
            min-height: 100vh;
            flex-direction: column;
        }
        main {
            flex: 1 0 auto;
        }
        .post-image {
            width: 100%;
            height: auto;
        }
        .nav-wrapper {
            background-color: rgb(251, 245, 239);
        }
        .brand-logo {
            font-family: 'Dawning of a New Day', cursive;
            font-size: 53px !important;
            margin-top: 4px;
            color: rgb(216, 163, 110) !important;
            font-weight: lighter !important;
            white-space: nowrap;
        }
        .brand-logo a{
            color: rgb(216, 163, 110) !important;
        }
        #title {
            color: rgb(216, 163, 110) !important;
        }
        nav {
            height: 80px;
        }
        .btn-floating i {
            font-size: 2rem;
        }

        .slide-social {
            padding: 0 32px !important;
        }
        body {
            background-color: rgb(248,237,235);
        }
        .page-footer{
            background-color: rgb(251, 245, 239);
        }
        h5{
            color: rgb(216, 163, 110) !important;
        }
        .subscribe{
            color: rgb(216, 163, 110) !important;
        }
        .btn-floating {
            background-color: rgb(216, 163, 110) !important;
        }
        nav .dropdown-trigger i {
            line-height: 80px !important;
        }
        .sidenav-trigger{
            line-height: 80px !important;
            height: 80px !important;
            display: flex;
            align-self: center;
        }
        .sidenav {
            background-color: rgb(251, 245, 239);
            color: black;
        }

        .sidenav li>a {
            color: rgb(216, 163, 110) !important;
        }

        .material-icons {
            color: rgb(216, 163, 110);
            height: 80px !important;
            line-height: 80px !important;
        }
        .dropdown-content {
            background-color: rgb(251, 245, 239);
        }

        .dropdown-content li>span {
            color: rgb(216, 163, 110) !important
        }

        .btn-floating {
            background-color: rgb(216, 163, 110) !important;
        }
        li p {
            padding: 0 32px;
            font-size: 14px;
            font-weight: 500;
        }
    </style>
</head>

<body>
    <nav>
        <div class="nav-wrapper">
            <div class="brand-logo center">
                <a href="{% url 'blogapp:home' %}">All Shapes  </a>
                •
                {% for category in post.categories.all %}
                <a href="{% url 'blogapp:category' category.path_name %}">{{category.name}}{% if not forloop.last %}/{%endif%}</a>
                {% endfor %}
            </div>
            <a href="" data-target="slide-out" class="sidenav-trigger right"><i class="material-icons">menu</i></a>
        </div>
    </nav>

    <!-- side menu for mobile -->
    <ul id="slide-out" class="sidenav">
        <li><a href="{% url 'blogapp:about' %}">About</a></li>
        <li><a target="_blank" href="https://mailchi.mp/33a744da0f70/allshapes">Newsletter</a></li>
        <li>
            <div class="divider"></div>
        </li>
        <li>
            <p>Social Media</p>
        </li>
        <li>
            <div class="slide-social"><a href="" class="waves-effect pulse btn-floating black">
                    <i class="fa fa-instagram"></i></a>
            </div>
        </li>
    </ul>

    <main>
        <div class="container">
            <div class="row" id="title">
                <h1>{{post.title}}</h1>
            </div>
            <div class="row">
                <div class="col l7 s12">
                    {% if post.image %}
                    <img class="post-image" src="{{post.image.url}}">
                    {% endif %}
                </div>
                <div class="col l5 s12 body-overflow">
                    {{post.body|safe}}
                </div>
            </div>
        </div>
    </main>

    <div class="container">
        <div id="disqus_thread"></div>
    </div>

    <footer class="page-footer z-depth-5">
        <div class="container">
            <div class="row">
                <div class="col s4">
                    <h5>Newsletter</h5>
                    <a class="subscribe" href="https://mailchi.mp/33a744da0f70/allshapes"
                        target="_blank">Subscribe</a>
                </div>
                <div class="col s4">
                    <a href="{% url 'blogapp:about' %}">
                        <h5>About</h5>
                    </a>
                </div>
                <div class="col s4">
                    <h5>Keep in Touch</h5>
                    <div class="row social-foot">
                        <a href="" class="waves-effect pulse btn-floating black">
                            <i class="fa fa-instagram"></i></a>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <script>

        /**
        *  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
        *  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables*/

        var disqus_config = function () {
            this.page.url = window.location.href;  // Replace PAGE_URL with your page's canonical URL variable
            this.page.identifier = {{ post.id }}
            
        }; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
        (function () { // DON'T EDIT BELOW THIS LINE
            var d = document, s = d.createElement('script');
            s.src = 'https://allshapes.disqus.com/embed.js';
            s.setAttribute('data-timestamp', +new Date());
            (d.head || d.body).appendChild(s);
        })();

        document.addEventListener('DOMContentLoaded', function () {
            var elems = document.querySelectorAll('.sidenav');
            var instances = M.Sidenav.init(elems, { edge: 'right' });
        });
    </script>
    <noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by
            Disqus.</a></noscript>

</body>

</html>

julieapp/templates/julieapp/dashboard.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">

    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!-- font -->
    <link href="https://fonts.googleapis.com/css2?family=Dawning+of+a+New+Day&display=swap" rel="stylesheet">
    <title>Dashboard</title>
    <style>
        .search-button {
            padding-top: 5px !important;
        }

        @media only screen and (max-width: 600px) {
            .overlay {
                opacity: 1 !important;
            }

            nav .brand-logo {
                left: 155px !important;
                top: 5px;
                font-size: 34px !important;
            }

            i.right {
                padding-right: 23px;
            }

            .btn-small {
                width: 75px;
                padding: 0 5px;
            }
        }

        @media only screen and (max-width: 703px) {
            .brand-logo {
                font-size: 19px !important;
            }

            h4 {
                font-size: 20px;
                white-space: nowrap;
            }

            p {
                font-size: 12px;
            }
        }

        .brand-logo {
            font-family: 'Dawning of a New Day', cursive;
            font-size: 53px !important;
            margin-top: 4px;
            color: rgb(216, 163, 110) !important;
            font-weight: lighter !important;
            white-space: nowrap;
        }

        .nav-wrapper {
            background-color: rgb(251, 245, 239);
        }

        nav {
            height: 80px;
        }

        nav ul a {
            display: block;
            line-height: 80px;
            color: rgb(216, 163, 110) !important;
            font-size: 15px;
        }

        nav .dropdown-trigger i {
            line-height: 80px !important;
        }

        .sidenav-trigger {
            color: rgb(216, 163, 110);
        }

        .material-menu {
            height: 80px !important;
            line-height: 80px !important;
            margin: 0 5px !important;
        }

        body {
            background-color: rgb(248, 237, 235);
        }

        .btn-floating {
            background-color: rgb(216, 163, 110) !important;
        }

        .btn {
            background-color: rgb(216, 163, 110) !important
        }

        .btn-small {
            background-color: rgb(216, 163, 110) !important
        }

        h4 {
            color: rgb(216, 163, 110) !important
        }

        .card-image img {
            height: 300px;
            width: 200px !important;
            object-fit: cover;
        }

        .card-row {
            display: flex;
            flex-direction: column;
        }

        .btn-row {
            display: flex;
            justify-content: center;
            align-items: center;
        }

        .card-action {
            display: flex;
            justify-content: space-evenly;
            padding: 10px 0px !important;
        }

        .select-wrapper input.select-dropdown:focus {
            border-bottom: 1px solid rgb(216, 163, 110);
        }

        .select-wrapper input {
            text-align: left;
        }

        .sidenav {
            background-color: rgb(251, 245, 239);
        }

        .sidenav li>a {
            color: rgb(216, 163, 110) !important;
        }

        .dropdown-content {
            background-color: rgb(251, 245, 239);
            color: rgb(216, 163, 110) !important;
        }

        .dropdown-content li>span {
            color: rgb(216, 163, 110) !important;
        }

        .select-dropdown {
            color: rgb(216, 163, 110) !important;
        }

        .search-bar {
            color: rgb(216, 163, 110) !important;
        }

        .search-bar input:focus {
            border-bottom: 1px solid rgb(216, 163, 110);
        }

        .card {
            background-color: rgb(251, 245, 239);
        }
    </style>
</head>

<body>
    <nav>
        <div class="nav-wrapper">
            <a href="{% url 'julieapp:dashboard' %}" class="brand-logo center">All Shapes • Dashboard</a>
            <ul class="right hide-on-med-and-down">
                <li><a target="_blank" href="https://us2.admin.mailchimp.com/">Newsletter</a></li>
                <li><a target="_blank" href="https://disqus.com/admin/">Disqus</a></li>
                <li><a href="{% url 'julieapp:logout' %}">Logout</a></li>
            </ul>
            <a href="#" data-target="slide-out" class="sidenav-trigger right"><i
                    class="material-icons material-menu">menu</i></a>
        </div>
    </nav>

    <!-- side menu for mobile -->
    <ul id="slide-out" class="sidenav">
        <li><a target="_blank" href="https://us2.admin.mailchimp.com/">Newsletter</a></li>
        <li><a target="_blank" href="https://disqus.com/admin/">Disqus</a></li>
        <li>
            <div class="divider"></div>
        </li>
        <li><a href="{% url 'julieapp:logout' %}">Logout</a></li>
    </ul>
    <!-- fixed create button -->
    <div class="fixed-action-btn">
        <a href="{% url 'julieapp:create' %}" class="btn-floating btn-large">
            <i class="large material-icons">add</i>
        </a>
    </div>
    <!-- search-bar -->
    <div class="container">
        <form class="row" action="{% url 'julieapp:dashboard' %}" method="GET">
            <div class="input-field col m8 s12">
                <input class="search-bar" name="search" type="text" placeholder="Search">
            </div>
            <div class="input-field col m2 s8">
                <select name="category">
                    <option value="">All categories</option>
                    {% for category in categories %}
                    <option {% if selected_category == category.name %} selected {% endif %}value="{{category.name}}">
                        {{category.name}}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="input-field search-button col m2 s4">
                <button class="btn" type="submit">Search</button>
            </div>
        </form>
        <!-- blog post cards -->
        <div class="row">
            {% for post in posts %}
            <div class="col xl6 m12 s12 card-row">
                <h4>{{ post.title }}</h4>
                <div class="card horizontal hoverable">
                    <div class="card-image">
                        {% if post.image %}
                        <a target="_blank" href="{% url 'blogapp:post' post.id %}"><img src="{{post.image.url}}"></a>
                        {% endif %}
                    </div>
                    <class class="card-stacked">
                        <div class="card-content">
                            <p><b>Category:</b>
                                {% for category in post.categories.all %}{{category.name}}{% if not forloop.last %}/{%endif%}{% endfor %}
                            </p>
                            <br>
                            <p><b>Description:</b> {{post.description}}</p>
                        </div>
                        <div class="card-action">
                            <a href="{% url 'julieapp:edit' post.id %}" class="waves-effect waves-light btn-small"><i
                                    class="material-icons right">create</i><span class="hide-on-small-only">Edit
                                    Post</span></a>
                            <a target="_blank" href="{% url 'blogapp:post' post.id %}"
                                class="waves-effect waves-light btn-small view-post"><i
                                    class="material-icons right">visibility</i><span class="hide-on-small-only">View
                                    Post</span></a>
                        </div>
                    </class>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>

    <script>
        document.addEventListener('DOMContentLoaded', function () {
            var elems = document.querySelectorAll('select');
            var instances = M.FormSelect.init(elems, {});
        })
        document.addEventListener('DOMContentLoaded', function () {
            var elems = document.querySelectorAll('.sidenav');
            var instances = M.Sidenav.init(elems, { edge: 'right' });
        });
        // var instance = M.FormSelect.getInstance(elem);
        // document.querySelector('.select-dropdown.dropdown-trigger').style.width = '20px !important'
    </script>
</body>

</html>